### ISSUE TITLE
XParse JProp wrong prefix

### ISSUE THREAD

**Issue by markoczy** [markoczy/xtools#2]
```yml
topic:
  name: users
  partitions-num: 6
  replication-factor: 3
server:
  port: 9080
spring:
  kafka:
    bootstrap-servers:
      - mybootstrap.confluent.cloud:9092   (1)  
    properties:
      # CCloud broker connection parameters
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      request.timeout.ms: 20000
      retry.backoff.ms: 500
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="ccloud_key" password="ccloud_secret";   (2) 
      security.protocol: SASL_SSL

      # CCloud Schema Registry Connection parameter
      schema.registry.url: https://schema-registry.aws.confluent.cloud   (3)  
      basic.auth.credentials.source: USER_INFO   (4)  
      schema.registry.basic.auth.user.info: sr_ccloud_key:sr_ccloud_key   (5) 
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:
logging:
  level:
    root: info
```

```conf
topic.replication-factor = 3
topic.replication-factor.name = users
topic.replication-factor.name.partitions-num = 6
topic.server.port = 9080
topic.server.spring.kafka.producer.key-serializer = org.apache.kafka.common.serialization.StringSerializer
topic.server.spring.kafka.producer.key-serializer.value-serializer = io.confluent.kafka.serializers.KafkaAvroSerializer
topic.server.spring.kafka.producer.template.bootstrap-servers[0] = mybootstrap.confluent.cloud:9092   (1)
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.sasl.mechanism = PLAIN
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.sasl.mechanism.security.protocol = SASL_SSL
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.sasl.mechanism.security.protocol.schema.registry.basic.auth.user.info = sr_ccloud_key:sr_ccloud_key   (5)
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.sasl.mechanism.security.protocol.schema.registry.basic.auth.user.info.schema.registry.url = https://schema-registry.aws.confluent.cloud   (3)
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.sasl.mechanism.security.protocol.schema.registry.basic.auth.user.info.schema.registry.url.basic.auth.credentials.source = USER_INFO   (4)
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.sasl.mechanism.security.protocol.schema.registry.basic.auth.user.info.schema.registry.url.basic.auth.credentials.source.ssl.endpoint.identification.algorithm = https
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.sasl.mechanism.security.protocol.schema.registry.basic.auth.user.info.schema.registry.url.basic.auth.credentials.source.ssl.endpoint.identification.algorithm.request.timeout.ms = 20000
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.sasl.mechanism.security.protocol.schema.registry.basic.auth.user.info.schema.registry.url.basic.auth.credentials.source.ssl.endpoint.identification.algorithm.request.timeout.ms.retry.backoff.ms = 500
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.sasl.mechanism.security.protocol.schema.registry.basic.auth.user.info.schema.registry.url.basic.auth.credentials.source.ssl.endpoint.identification.algorithm.request.timeout.ms.retry.backoff.ms.sasl.jaas.config = org.apache.kafka.common.security.plain.PlainLoginModule required username="ccloud_key" password="ccloud_secret";   (2)
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.consumer.group-id = group_id
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.consumer.group-id.auto-offset-reset = earliest
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.consumer.group-id.auto-offset-reset.key-deserializer = org.apache.kafka.common.serialization.StringDeserializer
topic.server.spring.kafka.producer.template.bootstrap-servers.properties.consumer.group-id.auto-offset-reset.key-deserializer.value-deserializer = io.confluent.kafka.serializers.KafkaAvroDeserializer
topic.server.spring.logging.level.root = info
```
